### PR TITLE
fix awesome_print issue

### PR DESCRIPTION
**Pull request by gj**

### CODE REVIEW

**Comment by gj** [comment]
fixes:
* https://github.com/learn-co-students/using-bundler-v-000/issues/313
* https://github.com/learn-co-curriculum/using-bundler/issues/39

**Comment by AnnJohn** [comment]
'cc @mendelB @PeterBell

**Comment by PeterBell** [comment]
LGTM - thanks @gj

**Comment by gj** [comment]
I think the two issues above can be closed now @PeterBell

**Comment by PeterBell** [comment]
Done - thanks @gj ⭐

**Pull request merged**
